export const CHATLIST_LOADING = 'CHATLIST_LOADING';
export const CHATLIST_Fetch_SUCCESS = 'CHATLIST_Fetch_SUCCESS';
export const CHATLIST_Fetch_FAILED = 'CHATLIST_Fetch_FAILED';


//* search chat user
export const SEARCH_CHATUSER_LOADING = 'SEARCH_CHATUSER_LOADING';
export const SEARCH_CHATUSER_SUCCESS = 'SEARCH_CHATUSER_SUCCESS';
export const SEARCH_CHATUSER_FAILED = 'SEARCH_CHATUSER_FAILED';